/**:
  ros__parameters:
    mujoco_plugins:
      mujoco_camera_plugin:
        type: "mujoco_ros2_control_plugins/CameraPlugin"
        camera_publish_rate: 10.0
        camera:
          policy: streaming
          frame_name: camera_link
          info_topic: /camera/camera_info
          image_topic: /camera
          depth_topic: /camera/depth
      free_joint_state_publisher:
        type: "mujoco_ros2_control_plugins/FreeJointStatePublisherPlugin"
        frame_id: ""
        body_names: ["coke"]
        topic: "free_joint_states"
        publish_rate: 50.0
